spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jsbzww/springcloud
          searchPaths: respo
          username: 
          password:
      label: master
  application:
    name: law-config-server
  
server:
  port: 8769
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      