eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 5000

spring:
  application:
    name: law-gateway
    
zuul:
  routes:
    userapi:
      path: /userapi/**
      service-id: law-user